// Extra map markers that aren't in collectibles.lua.
// Same shape as COLLECTIBLES entries: { c, cls, n, x, y, z, label }
// `c` is a category short-code; extras can also provide explicit
// { story, type, subtype, progress } tags and optional map-pixel coords.
//
// Fabien's 6 phlegmatic-resonance feeding stations (fast-travel anchors).
// World coords sourced from the in-game widget log
// (MapData.Persistent.FeedingStation.* tag prefix).
window.MAP_EXTRAS = [
  { c:"HELPER", cls:"BP_NPC_Helper_EOTW_C",       n:"Helper.EOTW",       label:"EOTW",        x:  4842, y:  29589, z: 1943 },
  { c:"HELPER", cls:"BP_NPC_Helper_Guru_C",       n:"Helper.Guru",       label:"The Guru",    x:-22387, y:  55927, z: 1062 },
  { c:"HELPER", cls:"BP_NPC_Helper_MedicCarla_C", n:"Helper.MedicCarla", label:"Medic Carla", x: -4255, y:  52952, z: 1306 },
  { c:"HELPER", cls:"BP_NPC_Helper_MrLemon_C",    n:"Helper.MrLemon",    label:"Mr. Lemon",   x:-23180, y:  41841, z:  591 },
  { c:"HELPER", cls:"BP_NPC_Helper_Reggie_C",     n:"Helper.Reggie",     label:"Reggie",      x:-15997, y:  25306, z: 1503 },
  { c:"HELPER", cls:"BP_NPC_Helper_SexWorker_C",  n:"Helper.SexWorker",  label:"Sex Worker",  x:  2647, y:  -6410, z: 1948 },

  // Clan trainers.
  // trainers.lua only exposes sublevel-local transforms, so these are anchored
  // directly in hub-map pixel space at each venue's visible building footprint.
  {
    c: "TRAINER",
    cls: "BP_Niko_C",
    n: "Trainer.Niko",
    name: "Niko",
    clan: "Banu Haqim",
    location: "Aurora Pawn",
    story: "shared",
    type: "characters",
    subtype: "trainer",
    progress: "unknown",
    px: 780,
    py: 1082,
    icon: "assets/Map/Icons/Clan/banu-haqim.png",
    color: "#4f7ca8",
    description: "Banu Haqim clan trainer. The primary visible state places Niko around Aurora Pawn's Elysium cluster.",
  },
  {
    c: "TRAINER",
    cls: "BP_Onda_C",
    n: "Trainer.Onda.Primary",
    name: "Onda (Primary)",
    clan: "Lasombra",
    location: "Level-dependent spawn",
    story: "shared",
    type: "characters",
    subtype: "trainer",
    progress: "unknown",
    px: 1142,
    py: 1337,
    icon: "assets/Map/Icons/Clan/lasombra.png",
    color: "#5d5d70",
    description: "Primary Onda marker anchored to the level-dependent spawn point (current best pick).",
  },
  {
    c: "TRAINER",
    cls: "BP_Patience_C",
    n: "Trainer.Patience",
    name: "Patience",
    clan: "Toreador",
    location: "Aurora Pawn",
    story: "shared",
    type: "characters",
    subtype: "trainer",
    progress: "unknown",
    px: 810,
    py: 1146,
    icon: "assets/Map/Icons/Clan/toreador.png",
    color: "#2ca797",
    description: "Toreador clan trainer. Anchored to the visible Aurora Pawn / Elysium cluster state from the spring trainer dump.",
  },
  {
    c: "TRAINER",
    cls: "BP_Fletcher_C",
    n: "Trainer.Fletcher",
    name: "Fletcher",
    clan: "Ventrue",
    location: "Makom Bar",
    story: "shared",
    type: "characters",
    subtype: "trainer",
    progress: "unknown",
    px: 1212,
    py: 1238,
    icon: "assets/Map/Icons/Clan/ventrue.png",
    color: "#c4a146",
    description: "Ventrue clan trainer. Fletcher is mapped to Makom Bar, matching the visible Elysium-cluster state.",
  },
  {
    c: "TRAINER",
    cls: "BP_MrsThorn_C",
    n: "Trainer.MrsThorne",
    name: "Mrs Thorne",
    clan: "Tremere",
    location: "Wake the Dead",
    story: "shared",
    type: "characters",
    subtype: "trainer",
    progress: "unknown",
    px: 1014,
    py: 1054,
    icon: "assets/Map/Icons/Clan/tremere.png",
    color: "#8a48c2",
    description: "Tremere clan trainer. Using the primary visible Wake the Dead placement instead of the hidden shopkeeper variant.",
  },
  {
    c: "TRAINER",
    cls: "BP_Silky_C",
    n: "Trainer.Silky",
    name: "Silky",
    clan: "Brujah",
    location: "The Dutchman",
    story: "shared",
    type: "characters",
    subtype: "trainer",
    progress: "unknown",
    px: 730,
    py: 782,
    icon: "assets/Map/Icons/Clan/brujah.png",
    color: "#d9653f",
    description: "Brujah clan trainer. Silky is anchored to the visible Dutchman placement from the trainer actor dump.",
  },
];
